version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-backend
    restart: always
    ports:
      - "5556:5556"
    environment:
      - PORT=5556
      - MONGO_URI=mongodb://mongo:27017/expense_tracker
      - NODE_ENV=production
    depends_on:
      - mongo
    # command: npm run dev
    # volumes:
    #   - ./src:/app/src
    #   - /app/node_modules

  mongo:
    image: mongo:6
    container_name: expense-mongo
    restart: always
    ports:
      - "27017:27017"
    # volumes:
    #   - mongo_data:/data/db

volumes:
  mongo_data:
